stages:
  - containerization
  - deploy

variables:
  APPLICATION_NAME: user-manager
  DOCKER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  CERTIFICATE_DOMAIN: api.users.maximemoreillon.com

containerization:
  stage: containerization
  script:
    # If docker registry password provided, attempt login
    - >
      if [ -z ${CONTAINER_REGISTRY_PASSWORD} ];
      then echo "CONTAINER_REGISTRY_PASSWORD not set, skipping login";
      else echo "${CONTAINER_REGISTRY_PASSWORD}" | docker login ${CONTAINER_REGISTRY} --username ${CONTAINER_REGISTRY_USERNAME} --password-stdin;
      fi
    # Import environment variables from GitLab
    - cp ${ENV} ./.env
    # Build and push container
    - >
      docker build
      --build-arg HTTP_PROXY=$HTTP_PROXY
      --build-arg HTTPS_PROXY=$HTTPS_PROXY
      -t ${DOCKER_IMAGE}
      .
    - docker push ${DOCKER_IMAGE}
    - docker image rm ${DOCKER_IMAGE}

deployment:
  stage: deploy
  script:
    - envsubst < deployment.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
